[images]
  remote_images = ["https://source.unsplash.com/.*", "https://images.unsplash.com/.*", "https://ext.same-assets.com/.*", "https://ugc.same-assets.com/.*"]

[build]
  command = "pnpm install && pnpm build"
  publish = ".next"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ./"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "18"
  PNPM_VERSION = "10"
  NPM_FLAGS = "--legacy-peer-deps"
  NEXTJS_IGNORE_ESLINT = "true"
  NEXTJS_IGNORE_TYPECHECK = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@firebase/*", "firebase"]

[dev]
  command = "pnpm dev"
  port = 3000
  targetPort = 3000
  publish = ".next"
  autoLaunch = true